services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: always

networks:
  inception:

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/fducrot/data/mariadb

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password: 
    file: ../secrets/db_root_password.txt