listen=YES
listen_ipv6=NO

local_enable=YES
write_enable=YES

anonymous_enable=NO

chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_min_port=21000
pasv_max_port=21010

local_root=/var/www/html
user_sub_token=$USER

pasv_address=127.0.0.1